### ISSUE TITLE
how to train a siamese network

### ISSUE THREAD

**Issue by lacus2009** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#14] opened 2018-06-17 06:03 UTC
I am a beginner. What I could think of is just to see the trend of loss. How did you decide when to stop training?
Does the margin need to be tuned?
I have successfully run through your codes, but the result is not so ideal as you posted... 

Thanks a lot!

**Comment by herleeyandi** [comment] 2018-06-26 08:23
Hi @lacus2009 have you find the setting of training to get the best result?, I also have the same problem here.

**Comment by harveyslash** [comment] 2018-06-26 08:34
Duplicate of #15

**Closed as completed by harveyslash** 2018-06-26 08:34 UTC
